In [1]:
import pandas as pd
import numpy as np

As far as I could tell, you're trying to cast the 'Disability Type' horizontally.
One of the issues is that there are lots of duplicate entries, and also conflicting entries. (See below).

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/biodatascience/datasci611/gh-pages/data/project2_2019/DISABILITY_ENTRY_191102.tsv", sep='\t',
                       usecols=['Client ID', 'Disability Type (Entry)', 'Disability Determination (Entry)'],
                       na_values=['**'], header = 0)
df[(df['Client ID'] == 190642) & (df['Disability Type (Entry)'] == 'Chronic Health Condition (HUD)')]

,Client ID,Disability Determination (Entry),Disability Type (Entry)
1327,190642,No (HUD),Chronic Health Condition (HUD)
1336,190642,Yes (HUD),Chronic Health Condition (HUD)
6271,190642,No (HUD),Chronic Health Condition (HUD)
6280,190642,Yes (HUD),Chronic Health Condition (HUD)
6931,190642,No (HUD),Chronic Health Condition (HUD)
6940,190642,Yes (HUD),Chronic Health Condition (HUD)
39223,190642,No (HUD),Chronic Health Condition (HUD)
39232,190642,Yes (HUD),Chronic Health Condition (HUD)
39298,190642,No (HUD),Chronic Health Condition (HUD)
39307,190642,Yes (HUD),Chronic Health Condition (HUD)
39508,190642,No (HUD),Chronic Health Condition (HUD)
39517,190642,Yes (HUD),Chronic Health Condition (HUD)

To deal with this, I subset where 'Disability Determination (Entry)' is 'Yes (HUD)' and then drop duplicate entries.

In [3]:
df2 = df[df['Disability Determination (Entry)'] == 'Yes (HUD)'].drop_duplicates()
df2

,Client ID,Disability Determination (Entry),Disability Type (Entry)
7,397941,Yes (HUD),Mental Health Problem (HUD)
8,397941,Yes (HUD),Physical/Medical
22,130335,Yes (HUD),Chronic Health Condition (HUD)
23,130335,Yes (HUD),Physical/Medical
36,188933,Yes (HUD),Drug Abuse (HUD)
...,...,...,...
40618,367285,Yes (HUD),Mental Health Problem (HUD)
40866,199296,Yes (HUD),Mental Health Problem (HUD)
40875,378312,Yes (HUD),Physical/Medical
40909,379142,Yes (HUD),Mental Health Problem (HUD)
41283,363078,Yes (HUD),Physical/Medical

In [4]:
df3 = pd.pivot(df2, index = 'Client ID', columns = 'Disability Type (Entry)', values = 'Disability Determination (Entry)').fillna("No (HUD)")
df3

Disability Type (Entry),Alcohol Abuse (HUD),Both Alcohol and Drug Abuse (HUD),Chronic Health Condition (HUD),Developmental (HUD),Drug Abuse (HUD),HIV/AIDS (HUD),Mental Health Problem (HUD),Other,Other: Learning,Physical (HUD),Physical/Medical,Vision Impaired
Client ID,,,,,,,,,,,,
1096,No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD)
2024,No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD)
2054,No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD)
2142,No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),Yes (HUD),Yes (HUD),No (HUD)
2458,No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD)
...,...,...,...,...,...,...,...,...,...,...,...,...
1003586,No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD)
1003772,No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD)
1004044,No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD)
1004126,No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD)
1004212,No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),Yes (HUD),No (HUD),No (HUD),No (HUD),No (HUD),No (HUD)